language: node_js
cache:
  yarn: true
  directories:
    - node_modules

matrix:
  include:
    
    - node_js: "node"
      os: osx
    - node_js: "8"
      os: osx
    - node_js: "node"
      os: linux
    - node_js: "5"
      os: linux

before_script:
  - npm install -g gulp
  - cd project

script: gulp build_dist
